#!/bin/sh
#
# custodian-dinstall -- install packages in the upload queue

# CONFIG VARIABLES
CUSTODIAN_DINSTALL_BASEDIR=${CUSTODIAN_DINSTALL_BASEDIR:-"/srv/repo/upload/"}
CUSTODIAN_DINSTALL_SUITELIST=${CUSTODIAN_DINSTALL_SUITELIST:="jessie:stretch:buster"}

# Check if packages are of good status.
sanity_check()
{
# TODO FINISH IT
    return 0
}

# Install package into the suite
#
## Syntax:
#
# dinstall $suitename $filename
#
## Examples:
#
# dinstall stretch /path/to/abc.dsc
# dinstall buster /path/to/def.deb
#

# Return an iternation list for distributions.
_get_suitelist_iter()
{
    printf "%s" "$(printf "%s" "${CUSTODIAN_DINSTALL_SUITELIST}" | sed -e "s/:/ /g")"
}

_get_pkglist_iter()
{ (
    cd "${CUSTODIAN_DINSTALL_BASEDIR}" || exit 1
    if [ "x$1" != "x" ]; then
        basedist="$1"
    else
        basedist=""
    fi
    deblist="$(realpath $(find ./"${basedist}" -name "*.deb"))"
    dsclist="$(realpath $(find ./"${basedist}" -name "*.dsc"))"
    printf "%s%s" "${deblist}" "${dsclist}"
) }

dinstall()
{
    aptly repo add "$1" "$2"
}

dupdate()
{
    for i in $(_get_suitelist_iter); do
        aptly publish update "${i}"
    done
}

main()
{
    return 0
}

#main $@
